# Generated by Django 2.1.7 on 2019-03-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.TextField(choices=[('turn', 'Turn'), ('in_work', 'In_work'), ('done', 'Done')], default='turn', max_length=20, verbose_name='Статус')),
                ('time_planned', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
        ),
    ]
